### ISSUE TITLE
No possible answers printed on second guess for Feb 9 

### ISSUE THREAD

**Issue by johna777** [Cubevoid/mathler-solver#1]
Hi, I've enjoyed playing with your program but it failed on the Feb 9 puzzle. The goal is 15. The first guess I entered was -0+9+6 and the result was XXXGGG. the next guess was +1*9+6 and the result was XGXGGG.  At this point the program listed nothing after printing "possible answers".  The correct answer is 81/9+6  Cheers. ....John

**Comment by Cubevoid** [comment]
Thanks for bringing up the issue! 

The problem was that the script assumed that grey tiles were not in the answer at all, but it could be the case that, for example, a symbol had a green tile as well as a grey tile. 

I've updated the script so it should at least be correct now (although there are still significant speed optimizations to be done, especially for hard mode).
